language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get install -y cmake gcc-9 g++-9 lcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 90
  - sudo pip3 install conan codecov

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make VERBOSE=1
  - ./bin/unit_tests

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory lib --directory build --capture --no-external --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

branches:
  only:
  - main
